server:
  port:
    8000

eureka:
  instance:
    hostname: localhost

spring:
  output:
    ansi:
      enabled: always
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: company-service
          uri: http://localhost:8081
          predicates:
            - Path=/companyServices/**

        - id: AUTHENTICATION-SERVICE
          uri: http://localhost:8081
          predicates:
            - Path=/api/auth/**

        - id: compliance-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/auth/**


        - id: compliance-service
          uri: http://localhost:8083
          predicates:
            - Path=/compliance/**