#management:
#    endpoints:
#        web:
#            exposure:
#                include: info
#    info:
#        env:
#            enabled: true
#server:
#    port: 8989
#
#spring:
#    application:
#        name: API-GATEWAY-SERVICE
##    cloud:
##        gateway:
##            routes:
##                - id: COMPLIANCE-MASTER-SERVICE
##                  uri: lb://COMPLIANCE-MASTER-SERVICE
##                  predicates:
##                      - Path=/master/**
##
##                - id: COMPLIANCE-SERVICE
##                  uri: lb://COMPLIANCE-SERVICE
##                  predicates:
##                      - Path=/compliance/**
##
##                - id: COMPANY-SERVICE
##                  uri: lb://COMPANY-SERVICE
##                  predicates:
##                      - Path=/company/**,/login/**,/signup/**
##
##                - id: AUTHENTICATION-SERVICE
##                  uri: lb://AUTHENTICATION-SERVICE
##                  predicates:
##                    - Path=/auth/**
#eureka:
#  instance:
#    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka
#spring:
#  application:
#    name: api-gateway
#
#  cloud:
#    gateway:
#      routes:
#        - id: AUTHENTICATION-SERVICE
#          uri : http://localhost:8081
#          predicates :
#            - Path=/api/**
#
#        - id : company-service
#          uri: http://localhost:8082
#          predicates:
#            - Path=/api/v1/**

server:
  port:
    8000

eureka:
  instance:
    hostname: localhost

spring:
  output:
    ansi:
      enabled: always
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: company-service
          uri: http://localhost:8082
          predicates:
            - Path=/companyServices/**

        - id: AUTHENTICATION-SERVICE
          uri: http://localhost:8081
          predicates:
            - Path=/api/auth/**

